# Generated by Django 5.1.1 on 2024-10-08 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacultyID', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Description', models.CharField(max_length=300)),
                ('Deadline', models.DateTimeField(verbose_name='deadline')),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm.faculty')),
                ('Students', models.ManyToManyField(to='llm.student')),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('Description', models.CharField(max_length=300)),
                ('SubmissionDate', models.DateTimeField(verbose_name='submission')),
                ('Mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm.faculty')),
                ('Authors', models.ManyToManyField(to='llm.student')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=300)),
                ('Rating', models.IntegerField()),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm.project')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm.student')),
            ],
        ),
    ]
